name: Trivy Scan

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of the service'
        required: true
        type: string
      version:
        description: 'Version of the service'
        required: true
        type: string

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "SERVICE_NAME=${{ inputs.service_name }}" >> $GITHUB_ENV
          echo VERSION=$BRANCH_NAME >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'mosipdev/${{ env.SERVICE_NAME }}:${{ env.VERSION }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
